steps:
  # Build the Docker Compose services
  - name: 'docker/compose:1.26.2'
    entrypoint: '/bin/sh'  # Use the shell available in Alpine Linux
    args:
      - '-c'
      - |
        docker-compose build \
          --build-arg PROJECT_ID=$PROJECT_ID \
          --build-arg SHORT_SHA=$SHORT_SHA

  # Tag the built images with the desired tags
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'workspace_backend:latest', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/body-size-pred-repo/body-size-pred:$SHORT_SHA-backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'workspace_frontend:latest', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/body-size-pred-repo/body-size-pred:$SHORT_SHA-frontend']

  # Push the tagged images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/body-size-pred-repo/body-size-pred:$SHORT_SHA-backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/body-size-pred-repo/body-size-pred:$SHORT_SHA-frontend']

# Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'body-size-pred', '--image', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/body-size-pred-repo/body-size-pred:$SHORT_SHA-backend', '--platform', 'managed', '--region', 'asia-northeast1']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'body-size-pred-frontend', '--image', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/body-size-pred-repo/body-size-pred:$SHORT_SHA-frontend', '--platform', 'managed', '--region', 'asia-northeast1']