services:
  frontend:
    build: streamlit
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./storage:/storage
  backend:
    build: api
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage