# services:
#   frontend:
#     build: streamlit
#     ports:
#       - 8501:8501
#     depends_on:
#       - backend
#     volumes:
#         - ./storage:/storage
#   backend:
#     build: api
#     ports:
#       - 8080:8080
#     volumes:
#       - ./storage:/storage

version: "3.3"

services:
  backend:
    container_name: backend
    build: api/
    ports:
      - "8000:8000"
    networks:
      - deploy_network

  frontend:
    container_name: frontend
    build: streamlit/
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - deploy_network

networks:
  deploy_network:
    driver: bridge